name: Run E2E Tests

on: [pull_request]

jobs:
  run-unit-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: testdb
          MYSQL_ROOT_PASSWORD: testrootpass
          DATABASE_CLIENT: mysql
          DATABASE_URL: "mysql://root:@localhost:3306/manage-gym-api"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npx prisma generate
      - run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgres://docker:docker@localhost:5432/manage-gym?schema=public"
